name: Flutter CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi --release

      - name: Find APK file
        id: find_apk
        run: echo "::set-output name=apk_path::$(find . -name '*.apk' -print0 | xargs -0 ls -t | head -1)"

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App APK
          path: ${{ steps.find_apk.outputs.apk_path }}